# Generated by Django 3.1 on 2020-08-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_presence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cursus',
            constraint=models.UniqueConstraint(fields=('name',), name='unicite nom'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unicite prenom nom'),
        ),
    ]
